_commit: v1.8.2-12-g4261f1a
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: 'certificates.yaml,network-policies.yaml'
backups: true
helm: false
homepageEnabled: false
ingHost: cha.rlesthom.as
ingName: wordpress-cha-rlesthom-as
ingress: false
labels: 'app: wordpress'
name: wordpress
namespace: wordpress-cha-rlesthom-as
pvc: false
reloader: true
resources:
- backups.yaml
- configmaps.yaml
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- pvcs.yaml
- service-accounts.yaml
- services.yaml
- statefulsets.yaml
service: false
serviceAccount: false
svcAccountName: wordpress
svcName: wordpress
svcPortName: http
svcPortNum: 80
svcProtocol: TCP
svcSelector: 'app: wordpress'
svcTargetPort: http
svcType: ClusterIP
upstreamURL: https://wordpress.com/
url: https://github.com/charlesthomas/homelab-wordpress-cha.rlesthom.as
