---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: wordpress-cha-rlesthom-as
  namespace: longhorn # must be longhorn
spec:
  concurrency: 1
  cron: 0 0 * * *
  groups:
  - wordpress
  labels:
    app: wordpress-cha-rlesthom-as
  name: wordpress-cha-rlesthom-as
  retain: 7
  task: backup

