---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: wordpress
  namespace: longhorn # must be longhorn
spec:
  concurrency: 1
  cron: 0 0 * * *
  groups:
  - wordpress
  labels:
    app: wordpress
  name: wordpress
  retain: 7
  task: 

