---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cha.rlesthom.as
  namespace: wordpress-cha-rlesthom-as
spec:
  commonName: 'cha.rlesthom.as'
  dnsNames:
  - 'cha.rlesthom.as'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: cha.rlesthom.as
