---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress
  namespace: wordpress-cha-rlesthom-as
spec:
  target:
    name: wordpress
    deletionPolicy: Delete
  data:
    - secretKey: wordpress-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: a724a0aa-0c4f-4ad7-91fc-3d3f83f44a0e
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb
  namespace: wordpress-cha-rlesthom-as
spec:
  target:
    name: mariadb
    deletionPolicy: Delete
  dataFrom:
    - sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: wordpress-cha-rlesthom-as-mariadb
        metadataPolicy: None
