---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress
  namespace: wordpress-cha-rlesthom-as
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
  namespace: wordpress-cha-rlesthom-as
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.4.3
automountServiceAccountToken: false
