---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress-cha-rlesthom-as
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: wordpress
