---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd # MUST be argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/charlesthomas/homelab-wordpress-cha.rlesthom.as
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress-cha-rlesthom-as
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
  ignoreDifferences:
    - kind: Service
      jqPathExpressions:
        - .spec.ports[].nodePort
